-- test cases generated by ChatGPT

select id, name, email from Users where active = true;
update users set last_login = now() where id = 1;
delete from sessions where user_id = 1;
insert into orders (user_id, product_id, quantity) values (1, 2, 3);

select a.name, b.amount
from customers a
inner join transactions b on a.id = b.customer_id
where a.country = 'USA and Canada'
and b.amount > 100
order by b.date desc;

create table products (
    id serial primary key,
    name varchar(100) not null,
    price decimal(10, 2) not null check (price > 0)
);

create table orders (
    id serial primary key,
    user_id int references users(id),
    product_id int references products(id),
    quantity int check (quantity > 0)
);

create procedure get_customer_balance(in customer_id int)
begin
    declare balance decimal(10, 2);
    select sum(amount) into balance from transactions where customer_id = customer_id;
    select balance;
end;

create view active_users as
select id, name, email
from users
where active = true;

create index idx_user_email on users (email);
